development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: gabble_development
  pool: 5
  username: vincent
  password: passw0rd

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: gabble_test
  pool: 5
  username: vincent
  password: passw0rd
